name: Mirror Dockerhub to Github

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  PLATFORMS: linux/arm/v7,linux/arm64/v8,linux/amd64

jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Install Buildx
        uses: docker/setup-buildx-action@v1.0.4
      - name: Build
        run: |
          for tag in $(cat ./images/debian); do
            docker buildx build \
              --platform $PLATFORMS \
              --build-arg IMAGE=debian \
              --build-arg VERSION=$tag \
              --tag ghcr.io/${{ github.repository }}/debian:$tag \
              --push \
              .
          done
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Install Buildx
        uses: docker/setup-buildx-action@v1.0.4
      - name: Build
        run: |
          for tag in $(cat ./images/alpine); do
            docker buildx build \
              --platform $PLATFORMS \
              --build-arg IMAGE=alpine \
              --build-arg VERSION=$tag \
              --tag ghcr.io/${{ github.repository }}/alpine:$tag \
              --push \
              .
          done
